name: authentication_repository


environment:
  sdk: ">=2.19.0-444.6.beta <3.0.0"

dev_dependencies:
  flutter_lints: ^1.0.4  

dependencies:
  equatable: ^2.0.3
  firebase_auth: ^4.6.2
  google_sign_in: ^6.1.3
  